DROP TABLE IF EXISTS users, items, booking, comments, requests;

CREATE TABLE IF NOT EXISTS users (
  id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  name           VARCHAR(255)  NOT NULL,
  email          VARCHAR(512)  NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    description  VARCHAR(512)  NOT NULL,
    requester_id BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_date TIMESTAMP     WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items (
  id             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
  name           VARCHAR(255)  NOT NULL,
  description    VARCHAR(512),
  is_available   BOOLEAN       NOT NULL,
  owner_id       BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  request_id     BIGINT        REFERENCES requests(id) ON DELETE CASCADE,
  CONSTRAINT pk_item PRIMARY KEY (id)
  );

 CREATE TABLE IF NOT EXISTS booking (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    start_date   TIMESTAMP     WITHOUT TIME ZONE NOT NULL,
    end_date     TIMESTAMP     WITHOUT TIME ZONE NOT NULL,
    item_id      BIGINT        NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    booker_id    BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status       VARCHAR(16)   NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments(
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    text         VARCHAR(512)  NOT NULL,
    item_id      BIGINT        NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    author_id    BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_date TIMESTAMP     WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);